### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by mhamidjamil**
PR contains major changes and fixes:
- #56 
- #136 
- #126 
- #109 (mining script is running which occupy two threads which causes overheat issue I solved it by placing two fans on top of it)
- Also added support for ESP32-Cam and USB camera module.

### CODE REVIEW

**Review by wasey-rao — APPROVED** [review]
I'm approving this but I think you should consider creating requirement.txt file in project.

**Comment by wasey-rao** [comment]
@SaffiUllah1999 pylint issues are resolved by @mhamidjamil please let him know next priority, for now I'm merging this PR.

**Comment by wasey-rao** [comment]
@SaffiUllah1999 pylint issues are resolve by @mhamidjamil please merge this PR and let him know next priority.

**Review by SaffiUllah1999 — APPROVED** [review]
@wasey-rao is right we should create a requirements.txt file and also updated files address ASAP, but for now I'm approving and merging this PR

**Pull request merged**
